api_platform:
    swagger:
        versions: [3]
    mapping:
        paths:
            - '%kernel.project_dir%/src/Domain/Forum/Entity'
    formats:
        json:
            mime_types:
                - 'application/json'
        jsonld:
            mime_types:
                - 'application/ld+json'
        html:
            mime_types:
                - 'text/html'
    patch_formats:
        json:
            - 'application/merge-patch+json'
