doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/User/Entity'
                prefix: 'App\Domain\User\Entity'
                alias: User
            Forum:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Forum/Entity'
                prefix: 'App\Domain\Forum\Entity'
                alias: User
