security:
    enable_authenticator_manager: true
    password_hashers:
        App\Bridge\Security\SecurityUser: 'plaintext'
    providers:
        security_user_provider:
            id: App\Bridge\Security\SecurityUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            provider: security_user_provider
            http_basic: ~

    access_control:
        - { path: ^/api, roles: ROLE_USER }
