version: '3.8'

services:

    php:
        build:
            context: './.docker/php'
            dockerfile: 'Dockerfile'
            args:
                uid: '1000'
                user: 'app'
        user: '1000'
        working_dir: '/app'
        volumes:
            - './:/app'
        ports:
            - '9000:9000'
        depends_on:
            - 'mysql'

    server:
        build:
            context: './.docker/nginx'
            dockerfile: 'Dockerfile'
        working_dir: '/app'
        volumes:
            - './:/app'
        ports:
            - '8080:80'
        depends_on:
            - 'php'

    mysql:
        image: 'mysql:5.7'
        environment:
            MYSQL_DATABASE: forum
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
