services:
    App\Domain\User\Command\Handler\:
      resource: '%kernel.project_dir%/src/Domain/User/Command/Handler'
      autowire: true
      tags:
          - { name: messenger.message_handler,  bus: command.bus }
