services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Bridge\ApiPlatform\DeleteOperationDeserializeListener:
        autowire: true
        arguments:
            - '@api_platform.serializer'
            - '@api_platform.serializer.context_builder'
            - '@api_platform.metadata.resource.metadata_factory'
        tags:
            - { name: 'kernel.event_listener', 'event': 'kernel.request', method: 'onKernelRequest', priority: -100 }

    App\Domain\EventSubscriber\:
        resource: '../src/Domain/EventSubscriber/*'
        autowire: true
        tags:
            - { name: messenger.message_handler }
